# Generated by Django 3.2.7 on 2021-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='RAM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ROM',
            field=models.IntegerField(),
        ),
    ]
