# Generated by Django 3.2.7 on 2021-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop_app', '0002_auto_20210914_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=32),
        ),
    ]
